### ISSUE TITLE
Install Centos7 Python 3.6 failed

### ISSUE THREAD

**Issue by MikeLynx** [clearlinux/autospec#118]
Hello I tried to install the version 1.2.0 on Centos7

I have installed :
Python 3.6.4 
Flake3.5
pycurl-7.43.0.1
toml-0.9.4
mock-2.0.0
coverage-4.5

I did : 
python3.6 setup.py install

but I get following error :

`[root@prvllxsvr5dev20 autospec-1.2.0]# python3.6 setup.py install
running install
running bdist_egg
running egg_info
writing autospec.egg-info/PKG-INFO
writing dependency_links to autospec.egg-info/dependency_links.txt
writing top-level names to autospec.egg-info/top_level.txt
reading manifest file 'autospec.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'autospec.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying autospec.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying autospec.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying autospec.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying autospec.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    include_package_data = True,
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 217, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 253, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 363, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 400, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
`

If someone could help me to understand what I have missed ?

Thank you

**Comment by MikeLynx** [comment]
My source folder was corrupted. Remove all and reinstall -- no errors
