### ISSUE TITLE
make autospec failure

### ISSUE THREAD

**Issue by SavinayDharmappa** [clearlinux/autospec#456]
We are trying to build rpm on clearlinux. Below are the steps we followed

1.  followed the steps mentioned in link https://docs.01.org/clearlinux/latest/guides/clear/autospec.html#setup-environment-to-build-source

2.  $cd clearlinux.

3.  $make clone_{package name} 
    ex:  $make clone_gedit.

4.  $cd packages/gedit/

5. $make autospec
 
make autospec command fails with below error,

```
Building`` package gedit round 1
gedit mock chroot at /var/lib/mock/clear-gedit
Password:
Traceback (most recent call last):
  File "../../projects/autospec/autospec/autospec.py", line 363, in <module>
    main()
  File "../../projects/autospec/autospec/autospec.py", line 237, in main
    package(args, url, name, archives, workingdir, infile_dict)
  File "../../projects/autospec/autospec/autospec.py", line 308, in package
    build.package(filemanager, args.mock_config, args.mock_opts, args.cleanup)
  File "/home/savi/test/clearlinux/projects/autospec/autospec/build.py", line 319, in package
    logfile="%s/results/mock_srpm.log" % download_path, cwd=download_path)
  File "/home/savi/test/clearlinux/projects/autospec/autospec/util.py", line 47, in call
    raise subprocess.CalledProcessError(returncode, full_args["args"], None)
subprocess.CalledProcessError: Command '['sudo', '/usr/bin/mock', '-r', '/home/savi/test/clearlinux/projects/common/conf/clear.cfg', '--buildsrpm', '--sources=./', '--spec=gedit.spec', '--uniqueext=gedit', '--result=results/', '--no-cleanup-after']' returned non-zero exit status 30.
make: *** [../common/Makefile.common:172: autospec] Error 1

```

**Comment by phmccarty** [comment]
Hi @SavinayDharmappa,

This type of errors could happen for any number of reasons. To find out more details, please take a look at your `results/root.log` and `results/build.log` files and search for any errors.

**Comment by phmccarty** [comment]
I will close this for now. If you can still reproduce the issue, please reopen.
