### ISSUE TITLE
Cannot build PECL packages

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#617]
With latest autospec, trying to build any PECL package leads to an exception:

```
Traceback (most recent call last):
  File "../../projects/autospec/autospec/autospec.py", line 355, in <module>
    main()
  File "../../projects/autospec/autospec/autospec.py", line 215, in main
    package(args, url, name, archives, workingdir, infile_dict)
  File "../../projects/autospec/autospec/autospec.py", line 231, in package
    content.process(filemanager)
  File "/home/pmccarty/clearlinux/projects/autospec/autospec/tarball.py", line 471, in process
    main_src = self.process_main_source(self.url)
  File "/home/pmccarty/clearlinux/projects/autospec/autospec/tarball.py", line 208, in process_main_source
    main_src = Source(url, '', src_path)
  File "/home/pmccarty/clearlinux/projects/autospec/autospec/tarball.py", line 46, in __init__
    self.set_prefix()
  File "/home/pmccarty/clearlinux/projects/autospec/autospec/tarball.py", line 60, in set_prefix
    prefix_method()
  File "/home/pmccarty/clearlinux/projects/autospec/autospec/tarball.py", line 75, in set_tar_prefix
    if 'package.xml' in lines and self.config.default_pattern in ['phpize']:
AttributeError: 'Source' object has no attribute 'config'
```

**Comment by bryteise** [comment]
Ugh that sucks. It is using the pattern so early it can only come from the url and not even the build_pattern config file. This is part of the need to rework the order (and the function) of what the top level autospec does to setup for builds.

I'll add a work around fix.
