### ISSUE TITLE
AttributeError raised for pypi_provides

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/autospec#625]
With recent changes to the Requirements class in support of adding/banning deps at the subpackage level, I am running into an exception:

```
Traceback (most recent call last):
  File "../../projects/autospec/autospec/autospec.py", line 355, in <module>
    main()
  File "../../projects/autospec/autospec/autospec.py", line 215, in main
    package(args, url, name, archives, workingdir, infile_dict)
  File "../../projects/autospec/autospec/autospec.py", line 302, in package
    specfile.write_spec()
  File "/home/pmccarty/clearlinux/projects/autospec/autospec/specfiles.py", line 90, in write_spec
    self.write_files_header()
  File "/home/pmccarty/clearlinux/projects/autospec/autospec/specfiles.py", line 290, in write_files_header
    if self.requirements.pypi_provides:
AttributeError: 'Requirements' object has no attribute 'pypi_provides'
```

**Comment by phmccarty** [comment]
@bryteise

**Comment by bryteise** [comment]
Interesting this escaped, it looks like because scan_for_configure wasn't called because that sets up the pypi_provides on the requirements class because it isn't defined by default X(.
